### ISSUE TITLE
2.2.4 doesn't compile

### ISSUE THREAD

**Issue by aienabled** [Noesis/Managed#2]
Hello!

https://github.com/Noesis/Managed/blob/57601edbc2c775e83796fd2ed4637c56422d6d56/Src/NoesisApp/Core/Src/Interactivity/TranslateZoomRotateBehavior.cs#L299

There is no such method in Point (multiplying Point on float).
I've fixed this by replacing all Point types in this method to Vector and using casting of Point to (Vector) where necessary.

Regards!

**Comment by s-fernandez-v** [comment]
Is it possible that you have changes in your custom branch that make the operation `(point - center)` return a Point instead of a Vector?

Because in our Point code it looks like this: https://github.com/Noesis/Managed/blob/master/Src/Noesis/Core/Src/Proxies/Point.cs#L79-L85

And Vector code:
https://github.com/Noesis/Managed/blob/master/Src/Noesis/Core/Src/Proxies/Vector.cs#L97-L103

This behavior is the same you can find in WPF code.

**Comment by aienabled** [comment]
Indeed. In my case it's returning Point instead of Vector and it seems to be this way for long time, something from legacy times :-) .
Sorry for posting the misleading issue. Next time I will pull the original repo and build it.
Regards!
